import * as cs from "@alloy-js/csharp";
import { Children } from "@alloy-js/core";

export interface SourceFileProps {
  path: string;
  children?: Children;
}

export function SourceFile(props: SourceFileProps): Children {
  return (
    <cs.SourceFile path={props.path}>
      {"// <auto-generated/>\n"}
      {props.children}
    </cs.SourceFile>
  );
}
