import * as cs from "@alloy-js/csharp";
import { Children } from "@alloy-js/core";

export interface ServerCodeSourceFileProps {
  path: string;
  children?: Children;
}

export function ServerCodeSourceFile(props: ServerCodeSourceFileProps): Children {
  return (
    <cs.SourceFile path={props.path}>
      {"// <auto-generated/>\n"}
      {props.children}
    </cs.SourceFile>
  );
}
