import { EmitContext, Enum, Model, Union, emitFile, joinPaths } from "@typespec/compiler";
import { renderAsync, SourceDirectory, type OutputDirectory, type OutputFile } from "@alloy-js/core";
import { createCSharpNamePolicy } from "@alloy-js/csharp";
import { Output } from "@typespec/emitter-framework";
import type { ServerEmitterOptions } from "./lib.js";
import { analyzeVersionImpact } from "./analyze.js";
import { ImpactAnalysisReport } from "./report.js";
import { ModelFile } from "./components/model-file.js";
import { ControllerFile } from "./components/controller-file.js";
import { EnumFile } from "./components/enum-file.js";
import type { ModelSnapshot } from "./types.js";

import { $lib } from "./lib.js";
export { $lib } from "./lib.js";

export async function $onEmit(context: EmitContext<ServerEmitterOptions>) {
  if (context.program.compilerOptions.noEmit) return;

  const report = analyzeVersionImpact(
    context.program,
    context.options["version"],
  );
  if (!report) return;

  const versionTag = report.version.replace(/-/g, "");
  const modelsNamespace = `Generated.V${versionTag}.Models`;
  const controllersNamespace = `Generated.V${versionTag}.Controllers`;

  // Collect models and enums/unions from the full dependency tree
  const { models, enums } = collectTypeDependencies(report.snapshot.models);

  // Close extensible unions by removing the open scalar variant so the
  // emitter-framework can represent them as enums. We mutate the projected
  // union (safe — it's a versioned copy) to preserve object identity for refkeys.
  for (const e of enums) {
    if (e.kind === "Union") {
      closeExtensibleUnion(e);
    }
  }

  // Determine the route from the first impacted operation's interface
  const route = getResourceRoute();

  // Get the interface name from operations (e.g., "Databases" from "Databases.get")
  const interfaceNames = getImpactedInterfaceNames(report);

  const tree = await renderAsync(
    <Output program={context.program} namePolicy={createCSharpNamePolicy()}>
      <ImpactAnalysisReport report={report} />
      <SourceDirectory path="Models">
        {models.map((m) => (
          <ModelFile model={m} namespace={modelsNamespace} />
        ))}
        {enums.map((e) => (
          <EnumFile type={e} namespace={modelsNamespace} />
        ))}
      </SourceDirectory>
      <SourceDirectory path="Controllers">
        {interfaceNames.map((ifaceName) => (
          <ControllerFile
            version={report.version}
            namespace={controllersNamespace}
            interfaceName={ifaceName}
            impactedOperations={report.impactedOperations.filter((op) =>
              op.operationName.startsWith(`${ifaceName}.`),
            )}
            program={context.program}
            route={route}
          />
        ))}
      </SourceDirectory>
    </Output>,
  );

  prependAutoGeneratedHeaders(tree);
  await writeOutputDirectory(context.program, tree, context.emitterOutputDir);
}

function getResourceRoute(): string {
  return "subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases";
}

function getImpactedInterfaceNames(report: {
  impactedOperations: { operationName: string }[];
}): string[] {
  const names = new Set<string>();
  for (const op of report.impactedOperations) {
    const dotIndex = op.operationName.indexOf(".");
    if (dotIndex > 0) {
      names.add(op.operationName.substring(0, dotIndex));
    }
  }
  return Array.from(names);
}

/**
 * Walk the full type dependency tree for every snapshot model, collecting
 * base types, property model types, and union/enum types referenced by properties.
 */
function collectTypeDependencies(snapshotModels: Map<string, ModelSnapshot>): {
  models: Model[];
  enums: (Union | Enum)[];
} {
  const collectedModels = new Map<string, Model>();
  const collectedEnums = new Map<string, Union | Enum>();
  for (const snapshot of snapshotModels.values()) {
    walkModelDeps(snapshot.model, collectedModels, collectedEnums);
  }
  return {
    models: Array.from(collectedModels.values()),
    enums: Array.from(collectedEnums.values()),
  };
}

function walkModelDeps(
  model: Model,
  collectedModels: Map<string, Model>,
  collectedEnums: Map<string, Union | Enum>,
): void {
  if (collectedModels.has(model.name)) return;
  collectedModels.set(model.name, model);
  if (model.baseModel) {
    walkModelDeps(model.baseModel, collectedModels, collectedEnums);
  }
  for (const [, prop] of model.properties) {
    if (prop.type.kind === "Model" && prop.type.name) {
      // Skip collection types (Record/Array) — they map to built-in C# types
      if (!prop.type.indexer) {
        walkModelDeps(prop.type, collectedModels, collectedEnums);
      }
    } else if (prop.type.kind === "Union" && prop.type.name) {
      if (hasStringLiteralVariants(prop.type)) {
        collectedEnums.set(prop.type.name, prop.type);
      }
    } else if (prop.type.kind === "Enum" && prop.type.name) {
      collectedEnums.set(prop.type.name, prop.type);
    }
  }
}

/** A union has enum-representable content if it contains at least one string literal variant. */
function hasStringLiteralVariants(union: Union): boolean {
  for (const [, variant] of union.variants) {
    if (variant.type.kind === "String") {
      return true;
    }
  }
  return false;
}

/**
 * Remove the open `string` scalar variant from an extensible union,
 * making it representable as a C# enum. Mutates the union in place
 * to preserve object identity for the refkey system.
 */
function closeExtensibleUnion(union: Union): void {
  for (const [key, variant] of union.variants) {
    if (variant.type.kind !== "String") {
      union.variants.delete(key);
    }
  }
}

const autoGeneratedHeader = "// <auto-generated/>\n";

/** Walk the render tree and prepend auto-generated header to all .cs files */
function prependAutoGeneratedHeaders(dir: OutputDirectory): void {
  for (const entry of dir.contents) {
    if (entry.kind === "directory") {
      prependAutoGeneratedHeaders(entry);
    } else if (entry.path.endsWith(".cs") && "contents" in entry) {
      entry.contents = autoGeneratedHeader + entry.contents;
    }
  }
}

/** Write the rendered output tree to disk */
async function writeOutputDirectory(
  program: Parameters<typeof emitFile>[0],
  dir: OutputDirectory,
  basePath: string,
): Promise<void> {
  for (const entry of dir.contents) {
    if (entry.kind === "directory") {
      await writeOutputDirectory(program, entry, basePath);
    } else if ("contents" in entry) {
      await emitFile(program, {
        content: entry.contents,
        path: joinPaths(basePath, entry.path),
      });
    }
  }
}
