import {
  EmitContext,
  Namespace,
  Model,
  Operation,
  Program,
  Type,
} from "@typespec/compiler";
import {
  unsafe_mutateSubgraphWithNamespace as mutateSubgraphWithNamespace,
} from "@typespec/compiler/experimental";
import {
  getVersioningMutators,
} from "@typespec/versioning";
import { SourceFile } from "@alloy-js/core";
import { Output, writeOutput } from "@typespec/emitter-framework";
import type { ServerEmitterOptions } from "./lib.js";

import { $lib } from "./lib.js";
export { $lib } from "./lib.js";
const { reportDiagnostic } = $lib;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface OperationImpact {
  operationName: string;
  reason: string;
}

interface VersionImpactReport {
  version: string;
  previousVersion: string | undefined;
  isFirstVersion: boolean;
  impactedOperations: OperationImpact[];
  allOperations: string[];
}

// ---------------------------------------------------------------------------
// JSX Components
// ---------------------------------------------------------------------------

function formatReport(report: VersionImpactReport): string {
  const sep = "=".repeat(70);
  const lines: string[] = [];

  lines.push(sep);
  lines.push("  Version Impact Analysis");
  lines.push("  Generated by @azure-tools/typespec-server-emitter");
  lines.push(sep);
  lines.push("");
  lines.push(
    `Version: ${report.version}${report.isFirstVersion ? " (first version)" : ""}`
  );
  if (report.previousVersion) {
    lines.push(`Compared against: ${report.previousVersion}`);
  }
  lines.push("");
  lines.push(`All operations: ${report.allOperations.join(", ")}`);
  lines.push("");

  if (report.impactedOperations.length === 0) {
    lines.push("✓ No impacted operations — no incremental controller needed.");
  } else {
    lines.push(
      `⚡ ${report.impactedOperations.length} impacted operation(s) — incremental controller needed:`
    );
    lines.push("");
    for (const impact of report.impactedOperations) {
      lines.push(`  • ${impact.operationName}`);
      lines.push(`    Reason: ${impact.reason}`);
      lines.push("");
    }
  }

  lines.push(sep);
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

export async function $onEmit(context: EmitContext<ServerEmitterOptions>) {
  if (context.program.compilerOptions.noEmit) return;

  const program = context.program;
  const targetVersion = context.options["version"];

  // Find the versioned service namespace
  const serviceNs = findServiceNamespace(program);
  if (!serviceNs) return;

  // Get versioning mutators
  const versioningMutators = getVersioningMutators(program, serviceNs);
  if (!versioningMutators || versioningMutators.kind !== "versioned") return;

  const snapshots = versioningMutators.snapshots;

  // Find the target version
  const targetIndex = snapshots.findIndex(
    (s) => s.version.value === targetVersion
  );
  if (targetIndex === -1) {
    reportDiagnostic(program, {
      code: "unknown-version",
      format: {
        version: targetVersion,
        available: snapshots.map((s) => s.version.value).join(", "),
      },
      target: program.getGlobalNamespaceType(),
    });
    return;
  }

  // Project the target version
  const { type: currentNs } = mutateSubgraphWithNamespace(
    program,
    [snapshots[targetIndex].mutator],
    serviceNs
  );
  const currentSnapshot = extractSnapshot(currentNs as Namespace);

  let report: VersionImpactReport;

  if (targetIndex === 0) {
    report = {
      version: targetVersion,
      previousVersion: undefined,
      isFirstVersion: true,
      impactedOperations: currentSnapshot.operations.map((op) => ({
        operationName: op.name,
        reason: "first version — all operations included",
      })),
      allOperations: currentSnapshot.operations.map((op) => op.name),
    };
  } else {
    const { type: previousNs } = mutateSubgraphWithNamespace(
      program,
      [snapshots[targetIndex - 1].mutator],
      serviceNs
    );
    const previousSnapshot = extractSnapshot(previousNs as Namespace);
    const impacted = diffSnapshots(previousSnapshot, currentSnapshot);

    report = {
      version: targetVersion,
      previousVersion: snapshots[targetIndex - 1].version.value,
      isFirstVersion: false,
      impactedOperations: impacted,
      allOperations: currentSnapshot.operations.map((op) => op.name),
    };
  }

  // Write output using the emitter framework
  const reportContent = formatReport(report);

  await writeOutput(
    program,
    <Output program={program}>
      <SourceFile path="impact-analysis.txt" filetype="txt">
        {reportContent}
      </SourceFile>
    </Output>,
    context.emitterOutputDir,
  );
}

// ---------------------------------------------------------------------------
// Snapshot extraction
// ---------------------------------------------------------------------------

interface VersionSnapshot {
  operations: OperationSnapshot[];
  models: Map<string, ModelSnapshot>;
}

interface OperationSnapshot {
  name: string;
  fingerprint: string;
}

interface ModelSnapshot {
  name: string;
  fingerprint: string;
}

function extractSnapshot(ns: Namespace): VersionSnapshot {
  const operations: OperationSnapshot[] = [];
  const models = new Map<string, ModelSnapshot>();

  for (const [, iface] of ns.interfaces) {
    for (const [, op] of iface.operations) {
      operations.push({
        name: `${iface.name}.${op.name}`,
        fingerprint: fingerprintOperation(op),
      });
    }
  }

  for (const [, op] of ns.operations) {
    operations.push({
      name: op.name,
      fingerprint: fingerprintOperation(op),
    });
  }

  for (const [, model] of ns.models) {
    models.set(model.name, {
      name: model.name,
      fingerprint: fingerprintModel(model),
    });
  }

  return { operations, models };
}

// ---------------------------------------------------------------------------
// Fingerprinting
// ---------------------------------------------------------------------------

function fingerprintOperation(op: Operation): string {
  const seen = new Set<Type>();
  const params = fingerprintModel(op.parameters, seen);
  const returnType = fingerprintType(op.returnType, seen);
  return `(${params}) => ${returnType}`;
}

function fingerprintModel(model: Model, seen: Set<Type> = new Set()): string {
  if (seen.has(model)) return `<circular:${model.name || "anonymous"}>`;
  seen.add(model);
  const props: string[] = [];
  for (const [name, prop] of model.properties) {
    props.push(`${name}${prop.optional ? "?" : ""}: ${fingerprintType(prop.type, seen)}`);
  }
  seen.delete(model);
  return `{ ${props.join(", ")} }`;
}

function fingerprintType(type: Type, seen: Set<Type> = new Set()): string {
  switch (type.kind) {
    case "Scalar":
      return type.name;
    case "Model": {
      if (type.indexer && type.name === "Array") {
        return `${fingerprintType(type.indexer.value, seen)}[]`;
      }
      if (type.name && type.name !== "" && !type.name.startsWith("(anonymous")) {
        return `${type.name}${fingerprintModel(type, seen)}`;
      }
      return fingerprintModel(type, seen);
    }
    case "Enum":
      return type.name;
    case "Union": {
      const variants: string[] = [];
      for (const [, v] of type.variants) {
        variants.push(fingerprintType(v.type, seen));
      }
      return variants.join(" | ");
    }
    case "Tuple": {
      const elements = type.values.map((v) => fingerprintType(v, seen));
      return `[${elements.join(", ")}]`;
    }
    default:
      return type.kind;
  }
}

// ---------------------------------------------------------------------------
// Diff
// ---------------------------------------------------------------------------

function diffSnapshots(
  prev: VersionSnapshot,
  curr: VersionSnapshot
): OperationImpact[] {
  const impacts: OperationImpact[] = [];
  const prevOpMap = new Map(prev.operations.map((o) => [o.name, o]));
  const currOpMap = new Map(curr.operations.map((o) => [o.name, o]));

  for (const [name, currOp] of currOpMap) {
    const prevOp = prevOpMap.get(name);
    if (!prevOp) {
      impacts.push({
        operationName: name,
        reason: "new operation (not present in previous version)",
      });
    } else if (prevOp.fingerprint !== currOp.fingerprint) {
      impacts.push({
        operationName: name,
        reason: `signature changed:\n      prev: ${prevOp.fingerprint}\n      curr: ${currOp.fingerprint}`,
      });
    }
  }

  for (const [name] of prevOpMap) {
    if (!currOpMap.has(name)) {
      impacts.push({
        operationName: name,
        reason: "removed in this version",
      });
    }
  }

  return impacts;
}

// ---------------------------------------------------------------------------
// Helper: find service namespace
// ---------------------------------------------------------------------------

function findServiceNamespace(program: Program): Namespace | undefined {
  for (const [, ns] of program.getGlobalNamespaceType().namespaces) {
    if (ns.decorators.some((d) => d.decorator.name === "$service")) {
      return ns;
    }
    for (const [, sub] of ns.namespaces) {
      if (sub.decorators.some((d) => d.decorator.name === "$service")) {
        return sub;
      }
    }
  }
  return undefined;
}
