import { SourceFile } from "@alloy-js/core";
import type { VersionImpactReport } from "./types.js";

export function ImpactAnalysisReport(props: { report: VersionImpactReport }) {
  const { report } = props;
  const sep = "=".repeat(70);
  const lines: string[] = [];

  lines.push(sep);
  lines.push("  Version Impact Analysis");
  lines.push("  Generated by @azure-tools/typespec-server-emitter");
  lines.push(sep);
  lines.push("");
  lines.push(
    `Version: ${report.version}${report.isFirstVersion ? " (first version)" : ""}`,
  );
  if (report.previousVersion) {
    lines.push(`Compared against: ${report.previousVersion}`);
  }
  lines.push("");
  lines.push(`All operations: ${report.allOperations.join(", ")}`);
  lines.push("");

  if (report.impactedOperations.length === 0) {
    lines.push("✓ No impacted operations — no incremental controller needed.");
  } else {
    lines.push(
      `⚡ ${report.impactedOperations.length} impacted operation(s) — incremental controller needed:`,
    );
    lines.push("");
    for (const impact of report.impactedOperations) {
      lines.push(`  • ${impact.operationName}`);
      lines.push(`    Reason: ${impact.reason}`);
      lines.push("");
    }
  }

  lines.push(sep);
  const content = lines.join("\n") + "\n";

  return (
    <SourceFile path="impact-analysis.txt" filetype="txt">
      {content}
    </SourceFile>
  );
}
